Feature/rides controllers create ride
victorandujar/BikeMeet-app-back pull request #25
Opened 2023-07-04 17:10 UTC by rom-dem

[X] createRide a ridesControllers
[X] actualitzar Mongoose perquè compili sense errors
[X] test

2023-07-04 17:36 UTC, victorandujar requested changes
Tot beee. Però has de resoldre el Bug aquest de merda q surt en cada endpoint que creem. Jo m'ho he estat mirant i no he trobat una solució factible, més que tractar-lo com un fals positiu.

2023-07-04 17:47 UTC, rom-dem commented
Help, Victor. No el puc ometre jo. Crec que ho has de fer tu! Gràcies!

2023-07-04 17:56 UTC, victorandujar commented
> Help, Victor. No el puc ometre jo. Crec que ho has de fer tu! Gràcies!

Jajaja cert. Sorry

2023-07-04 17:57 UTC, victorandujar approved these changes

2023-07-04 17:57 UTC, victorandujar commented
Ja està corregit :)

2023-07-05 09:31 UTC, Galan9999 reviewed
Perfect!

2023-07-05 09:31 UTC, merged